// ============================================================================
// crossbar_mac.sv
// Generated by: Claude Sonnet 4.6
// Codefest 6 — ECE 410/510 Spring 2026
// ----------------------------------------------------------------------------
// Description:
//   4×4 binary-weight crossbar MAC unit.
//   4 input lines (8-bit signed), 4 output accumulators (32-bit signed).
//   Weights encoded as +1 or -1, stored in a 4×4 register array.
//
//   Each clock cycle computes:
//     out[j] = Σ_i  weight[i][j] × in[i]   for j = 0..3
//
// Clock domain : Single clock domain. No clock crossings.
// Reset        : Synchronous, active-high.
//
// Port List:
//   clk         input  1-bit         System clock
//   rst         input  1-bit         Synchronous active-high reset
//   load_w      input  1-bit         Assert to load weight matrix
//   weight_in   input  4×4 × 2-bit  Weight values (+1=2'b01, -1=2'b11)
//   in_vec      input  4 × 8-bit    Input vector (INT8 signed)
//   valid_in    input  1-bit         Input vector valid
//   out_vec     output 4 × 32-bit   Output accumulator (signed)
//   valid_out   output 1-bit         Output valid
// ============================================================================

module crossbar_mac #(
    parameter int N          = 4,
    parameter int IN_WIDTH   = 8,
    parameter int OUT_WIDTH  = 32
) (
    input  logic                               clk,
    input  logic                               rst,
    input  logic                               load_w,
    input  logic signed [1:0]                  weight_in [0:N-1][0:N-1],
    input  logic signed [IN_WIDTH-1:0]         in_vec    [0:N-1],
    input  logic                               valid_in,
    output logic signed [OUT_WIDTH-1:0]        out_vec   [0:N-1],
    output logic                               valid_out
);

    // ── Weight register array ─────────────────────────────────────────────────
    logic signed [1:0] weight [0:N-1][0:N-1];

    always_ff @(posedge clk) begin
        if (rst) begin
            for (int i = 0; i < N; i++)
                for (int j = 0; j < N; j++)
                    weight[i][j] <= 2'sb01;
        end else if (load_w) begin
            for (int i = 0; i < N; i++)
                for (int j = 0; j < N; j++)
                    weight[i][j] <= weight_in[i][j];
        end
    end

    // ── Combinational MAC: compute partial sums ───────────────────────────────
    // Use combinational logic to sum all contributions, then register result
    logic signed [OUT_WIDTH-1:0] mac_comb [0:N-1];

    always_comb begin
        for (int j = 0; j < N; j++) begin
            mac_comb[j] = '0;
            for (int i = 0; i < N; i++) begin
                mac_comb[j] = mac_comb[j] +
                    ({{(OUT_WIDTH-IN_WIDTH){in_vec[i][IN_WIDTH-1]}}, in_vec[i]} *
                     {{(OUT_WIDTH-2){weight[i][j][1]}}, weight[i][j]});
            end
        end
    end

    // ── Register output on clock edge ─────────────────────────────────────────
    always_ff @(posedge clk) begin
        if (rst) begin
            for (int j = 0; j < N; j++)
                out_vec[j] <= '0;
            valid_out <= 1'b0;
        end else if (valid_in) begin
            for (int j = 0; j < N; j++)
                out_vec[j] <= mac_comb[j];
            valid_out <= 1'b1;
        end else begin
            valid_out <= 1'b0;
        end
    end

endmodule